# Creating DataFrames and Series in Pandas

## Learning Objectives

- Create DataFrames using different data structures
- Create Series using different data structures
- Export DataFrames to CSV, Excel, and JSON files
- Understand custom indexes in Series

In [1]:
import pandas as pd

## Creating a DataFrame Using a Dictionary of Lists

- Each key becomes a column name
- Each list becomes the column values
- All lists must have the same length

In [2]:
data = {
    "Name": ["DANIYA ARAIN", "UMAIR BHUTTO", "RAHEEM KATIAR"],
    "Age": [20, 21, 19],
    "City": ["HYDERABAD", "SUKKUR", "HYDERABAD"]
}

df = pd.DataFrame(data)

df

            Name  Age       City
0   DANIYA ARAIN   20  HYDERABAD
1   UMAIR BHUTTO   21     SUKKUR
2  RAHEEM KATIAR   19  HYDERABAD

## Creating a DataFrame Using a List of Lists

- Each inner list represents a row
- Column names can be specified using the columns parameter

In [3]:
data = [
    ["DANIYAL ARAIN", 20, "HYDERABAD"],
    ["UMAIR BHUTTO", 21, "SUKKUR"],
    ["RAHEEM KATIAR", 19, "HYDERABAD"]
]

df = pd.DataFrame(data, columns=["Name", "Age", "City"])

df

            Name  Age       City
0  DANIYAL ARAIN   20  HYDERABAD
1   UMAIR BHUTTO   21     SUKKUR
2  RAHEEM KATIAR   19  HYDERABAD

## Creating a DataFrame Using a List of Tuples

- Each tuple represents a row
- Column names are assigned using the columns parameter

In [4]:
data = [
    ("DANIYAL ARAIN", 20, "HYDERABAD"),
    ("UMAIR BHUTTO", 21, "SUKKUR"),
    ("RAHEEM KATIAR", 19, "HYDERABAD")
]

df = pd.DataFrame(data, columns=["Name", "Age", "City"])

df

            Name  Age       City
0  DANIYAL ARAIN   20  HYDERABAD
1   UMAIR BHUTTO   21     SUKKUR
2  RAHEEM KATIAR   19  HYDERABAD

## Creating a DataFrame Using a List of Dictionaries

- Each dictionary represents a row
- Dictionary keys become column names

In [5]:
data = [
    {"Name": "DANIYAL ARAIN", "Age": 20, "City": "HYDERABAD"},
    {"Name": "UMAIR BHUTTO", "Age": 21, "City": "SUKKUR"},
    {"Name": "RAHEEM KATIAR", "Age": 19, "City": "HYDERABAD"}
]

df = pd.DataFrame(data)

df

            Name  Age       City
0  DANIYAL ARAIN   20  HYDERABAD
1   UMAIR BHUTTO   21     SUKKUR
2  RAHEEM KATIAR   19  HYDERABAD

## Exporting a DataFrame to a CSV File

- to_csv() is used to save a DataFrame as a CSV file
- By default, row indexes are also exported

In [6]:
df.to_csv("output.csv")

## Exporting a CSV File Without Indexes

- index=False prevents row indexes from being written
- This produces a cleaner output file

In [7]:
df.to_csv("output.csv", index=False)

## Exporting a DataFrame to an Excel File

- to_excel() is used to save data in Excel format
- Excel files usually use the .xlsx extension

In [8]:
df.to_excel("output.xlsx")

## Exporting an Excel File Without Indexes

- index=False removes row indexes from the exported file

In [9]:
df.to_excel("output.xlsx", index=False)

## Exporting a DataFrame to a JSON File

- to_json() converts DataFrame data into JSON format
- JSON is commonly used for data exchange and APIs

In [10]:
df.to_json("output.json")

## Creating a Series Using a Dictionary

- Dictionary keys become indexes
- Dictionary values become Series values

In [11]:
data = {
    "NAME": "DANIYAL ARAIN",
    "AGE": 20,
    "CGPA": 3.71
}

s = pd.Series(data)

s

NAME    DANIYAL ARAIN
AGE                20
CGPA             3.71
dtype: object

## Creating a Series Using a List

- By default, Pandas assigns numeric indexes starting from 0

In [12]:
data = ["DANIYAL ARAIN", 20, 3.71]

s = pd.Series(data)

s

0    DANIYAL ARAIN
1               20
2             3.71
dtype: object

## Creating a Series Using a List with Custom Indexes

- Custom labels can be assigned using the index parameter
- These labels replace the default numeric indexes

In [13]:
data = ["DANIYAL ARAIN", 20, 3.71]

s = pd.Series(data, index=["NAME", "AGE", "CGPA"])

s

NAME    DANIYAL ARAIN
AGE                20
CGPA             3.71
dtype: object

## Creating a Series Using a Tuple

- Tuples can also be used as input data for a Series
- Default numeric indexes are assigned automatically

In [14]:
data = ("DANIYAL ARAIN", 20, 3.71)

s = pd.Series(data)

s

0    DANIYAL ARAIN
1               20
2             3.71
dtype: object

## Creating a Series Using a Tuple with Custom Indexes

- Custom labels improve readability
- Data can be accessed using these labels

In [15]:
data = ("DANIYAL ARAIN", 20, 3.71)

s = pd.Series(data, index=["NAME", "AGE", "CGPA"])

s

NAME    DANIYAL ARAIN
AGE                20
CGPA             3.71
dtype: object