# Data Inspection in Pandas

## Learning Objectives

- View the first rows of a DataFrame
- View the last rows of a DataFrame
- Display dataset information
- Understand the structure of a DataFrame

In [1]:
import pandas as pd

In [2]:
df = pd.read_json("sample_data.json")

## Viewing the First n Rows Using head()

- head(n) displays the first n rows of a DataFrame
- It is useful for quickly inspecting the beginning of a dataset

In [3]:
df.head(10)

,id,name,description,price,category,image
0,1,Apple iPhone 12,The Apple iPhone 12 features a 6.1-inch Super ...,999.00,Electronics,https://www.apple.com/newsroom/images/product/...
1,2,Samsung Galaxy S21,The Samsung Galaxy S21 features a 6.2-inch Dyn...,799.00,Electronics,https://images.samsung.com/is/image/samsung/p6...
2,3,Sony PlayStation 5,The Sony PlayStation 5 features an AMD Zen 2-b...,499.99,Electronics,https://www.sony.com/image/44baa604124b770c824...
3,4,LG OLED55CXPUA 55-inch 4K OLED TV,The LG OLED55CXPUA 55-inch 4K OLED TV features...,1599.99,Electronics,https://www.lg.com/us/images/tvs/md07501804/ga...
4,5,Bose QuietComfort 35 II Wireless Headphones,The Bose QuietComfort 35 II Wireless Headphone...,299.00,Electronics,https://assets.bose.com/content/dam/Bose_DAM/W...
5,6,Fitbit Versa 3 Smartwatch,The Fitbit Versa 3 Smartwatch features a built...,229.95,Electronics,https://www.fitbit.com/global/content/dam/fitb...
6,7,KitchenAid Stand Mixer,The KitchenAid Stand Mixer features a 5-quart ...,399.99,Home & Kitchen,https://www.kitchenaid.com/content/dam/global/...
7,8,Dyson V11 Absolute Cordless Vacuum,The Dyson V11 Absolute Cordless Vacuum feature...,699.99,Home Appliances,https://www.dysoncanada.ca/dam/dyson/images/pr...
8,9,Ninja Foodi Smart XL Grill,The Ninja Foodi Smart XL Grill features 6-in-1...,279.99,Home & Kitchen,https://www.ninjakitchen.com/medias/Ninja-OP50...
9,10,Canon EOS Rebel T8i DSLR Camera,The Canon EOS Rebel T8i DSLR Camera features a...,899.00,Electronics,https://www.canon.com.au/-/media/images/produc...

## Viewing the First 5 Rows Using head()

- If no value is provided, head() returns the first 5 rows by default

In [4]:
df.head()

,id,name,description,price,category,image
0,1,Apple iPhone 12,The Apple iPhone 12 features a 6.1-inch Super ...,999.00,Electronics,https://www.apple.com/newsroom/images/product/...
1,2,Samsung Galaxy S21,The Samsung Galaxy S21 features a 6.2-inch Dyn...,799.00,Electronics,https://images.samsung.com/is/image/samsung/p6...
2,3,Sony PlayStation 5,The Sony PlayStation 5 features an AMD Zen 2-b...,499.99,Electronics,https://www.sony.com/image/44baa604124b770c824...
3,4,LG OLED55CXPUA 55-inch 4K OLED TV,The LG OLED55CXPUA 55-inch 4K OLED TV features...,1599.99,Electronics,https://www.lg.com/us/images/tvs/md07501804/ga...
4,5,Bose QuietComfort 35 II Wireless Headphones,The Bose QuietComfort 35 II Wireless Headphone...,299.00,Electronics,https://assets.bose.com/content/dam/Bose_DAM/W...

## Viewing the Last n Rows Using tail()

- tail(n) displays the last n rows of a DataFrame
- It is useful for inspecting the end of a dataset

In [5]:
df.tail(10)

,id,name,description,price,category,image
10,11,Apple AirPods Pro,The Apple AirPods Pro feature active noise can...,249.00,Electronics,https://www.apple.com/v/airpods-pro/b/images/m...
11,12,Bose QuietComfort 35 II Wireless Headphones,The Bose QuietComfort 35 II Wireless Headphone...,299.00,Electronics,https://assets.bose.com/content/dam/Bose_DAM/W...
12,13,Fitbit Charge 4 Fitness Tracker,The Fitbit Charge 4 Fitness Tracker features G...,129.95,Electronics,https://www.fitbit.com/global/content/dam/fitb...
13,14,Samsung Galaxy Watch3,The Samsung Galaxy Watch3 features a rotating ...,399.99,Electronics,https://images.samsung.com/is/image/samsung/as...
14,15,Sony WH-1000XM4 Wireless Noise-Cancelling Head...,The Sony WH-1000XM4 Wireless Noise-Cancelling ...,349.99,Electronics,https://www.sony.com/image/1cdd6354c4cd21cc4f7...
15,16,Breville Barista Express Espresso Machine,The Breville Barista Express Espresso Machine ...,699.95,Home & Kitchen,https://www.breville.com/content/dam/breville/...
16,17,Keurig K-Elite Coffee Maker,The Keurig K-Elite Coffee Maker features a str...,169.99,Home & Kitchen,https://www.keurig.com/content/dam/global-ecom...
17,18,iRobot Roomba i7+ Robot Vacuum,The iRobot Roomba i7+ Robot Vacuum features au...,799.99,Home & Kitchen,https://store.irobot.com/default/i7-vacuuming-...
18,19,Ninja Foodi Digital Air Fry Oven,The Ninja Foodi Digital Air Fry Oven features ...,209.99,Home & Kitchen,https://www.ninjakitchen.com/static/img/produc...
19,20,Cuisinart ICE-70 Ice Cream Maker,The Cuisinart ICE-70 Ice Cream Maker features ...,139.99,Home & Kitchen,https://www.cuisinart.com/share/images/product...

## Viewing the Last 5 Rows Using tail()

- If no value is provided, tail() returns the last 5 rows by default

In [6]:
df.tail()

,id,name,description,price,category,image
15,16,Breville Barista Express Espresso Machine,The Breville Barista Express Espresso Machine ...,699.95,Home & Kitchen,https://www.breville.com/content/dam/breville/...
16,17,Keurig K-Elite Coffee Maker,The Keurig K-Elite Coffee Maker features a str...,169.99,Home & Kitchen,https://www.keurig.com/content/dam/global-ecom...
17,18,iRobot Roomba i7+ Robot Vacuum,The iRobot Roomba i7+ Robot Vacuum features au...,799.99,Home & Kitchen,https://store.irobot.com/default/i7-vacuuming-...
18,19,Ninja Foodi Digital Air Fry Oven,The Ninja Foodi Digital Air Fry Oven features ...,209.99,Home & Kitchen,https://www.ninjakitchen.com/static/img/produc...
19,20,Cuisinart ICE-70 Ice Cream Maker,The Cuisinart ICE-70 Ice Cream Maker features ...,139.99,Home & Kitchen,https://www.cuisinart.com/share/images/product...

## Displaying Dataset Information Using info()

- info() provides a summary of the DataFrame
- It displays the number of rows and columns
- It shows column names and data types
- It displays the count of non-null values
- It shows the memory usage of the DataFrame
- It helps identify missing values in a dataset

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           20 non-null     int64
 1   name         20 non-null     object
 2   description  20 non-null     object
 3   price        20 non-null     float64
 4   category     20 non-null     object
 5   image        20 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 1.1+ KB