# Data Selection, Filtering, and Aggregation in Pandas

## Learning Objectives

- Select single and multiple columns
- Slice rows from a DataFrame
- Filter data using single and multiple conditions
- Use the query() method for filtering
- Perform aggregation operations
- Generate descriptive statistics
- Retrieve DataFrame structure information

In [1]:
import pandas as pd

In [2]:
data = {
    "Name": ["DANIYAL", "UMAR", "UMAIR", "RAHEEM", "HASNAIN", "QAYOOM", "NABEEL", "PREM"],
    "Age": [20, 24, 16, 56, 34, 46, 39, 28],
    "Salary": [100000, 40000, 85000, 44000, 90000, 34000, 45000, 78000],
    "Performance Score": [85, 90, 78, 92, 88, 95, 80, 89]
}

df = pd.DataFrame(data)

df

      Name  Age  Salary  Performance Score
0  DANIYAL   20  100000                 85
1     UMAR   24   40000                 90
2    UMAIR   16   85000                 78
3   RAHEEM   56   44000                 92
4  HASNAIN   34   90000                 88
5   QAYOOM   46   34000                 95
6   NABEEL   39   45000                 80
7     PREM   28   78000                 89

## Selecting a Single Column

- A single column can be selected using square brackets
- Selecting a single column returns a Series

In [3]:
df["Name"]

0    DANIYAL
1       UMAR
2      UMAIR
3     RAHEEM
4    HASNAIN
5     QAYOOM
6     NABEEL
7       PREM
Name: Name, dtype: object

## Selecting Multiple Columns

- Multiple columns can be selected by passing a list of column names
- Selecting multiple columns returns a DataFrame

In [4]:
subset = df[["Name", "Performance Score"]]

subset

      Name  Performance Score
0  DANIYAL                 85
1     UMAR                 90
2    UMAIR                 78
3   RAHEEM                 92
4  HASNAIN                 88
5   QAYOOM                 95
6   NABEEL                 80
7     PREM                 89

## Slicing Rows

- Slicing is used to select a range of rows
- The starting index is included
- The ending index is excluded

In [5]:
df[2:5]

      Name  Age  Salary  Performance Score
2    UMAIR   16   85000                 78
3   RAHEEM   56   44000                 92
4  HASNAIN   34   90000                 88

## Filtering Rows Using a Single Condition

- Rows can be filtered using comparison operators
- Only rows satisfying the condition are returned

In [6]:
high_salary = df[df["Salary"] > 50000]

high_salary

      Name  Age  Salary  Performance Score
0  DANIYAL   20  100000                 85
2    UMAIR   16   85000                 78
4  HASNAIN   34   90000                 88
7     PREM   28   78000                 89

## Finding the Employee with the Maximum Salary

- max() returns the highest value in a column
- The matching row is filtered from the DataFrame

In [7]:
max_sal = df[df["Salary"] == df["Salary"].max()]

max_sal

      Name  Age  Salary  Performance Score
0  DANIYAL   20  100000                 85

## Displaying Specific Columns for the Employee with the Maximum Salary

- Multiple columns can be selected after filtering
- This helps focus only on the required information

In [8]:
df[["Name", "Salary"]][df["Salary"] == df["Salary"].max()]

      Name  Salary
0  DANIYAL  100000

## Filtering Rows Using Multiple Conditions with AND

- The & operator represents the AND condition
- Parentheses are required around each condition
- Both conditions must be true

In [9]:
filtered = df[ (df["Salary"] > 50000) & (df["Age"] > 25) ]

filtered

      Name  Age  Salary  Performance Score
4  HASNAIN   34   90000                 88
7     PREM   28   78000                 89

## Filtering Rows Using Multiple Conditions with OR

- The | operator represents the OR condition
- At least one condition must be true

In [10]:
filtered2 = df[ (df["Age"] > 25) | (df["Performance Score"] > 90) ]

filtered2

      Name  Age  Salary  Performance Score
3   RAHEEM   56   44000                 92
4  HASNAIN   34   90000                 88
5   QAYOOM   46   34000                 95
6   NABEEL   39   45000                 80
7     PREM   28   78000                 89

## What is the query() Method

- query() is used to filter rows using string expressions
- It improves readability for complex conditions
- Column names can be used directly in expressions
- Backticks are used for column names containing spaces
- The @ symbol is used to reference Python variables

## Filtering Rows Using query()

- Conditions are written as strings
- The result is similar to Boolean indexing

In [11]:
high_salary = df.query("Salary > 50000")

high_salary

      Name  Age  Salary  Performance Score
0  DANIYAL   20  100000                 85
2    UMAIR   16   85000                 78
4  HASNAIN   34   90000                 88
7     PREM   28   78000                 89

## Finding the Employee with the Maximum Salary Using query()

- Aggregate functions can be used inside query()
- The matching row is returned

In [12]:
max_sal = df.query("Salary == Salary.max()")

max_sal

      Name  Age  Salary  Performance Score
0  DANIYAL   20  100000                 85

## Displaying Specific Columns Using query()

- Filtering and column selection can be combined

In [13]:
df.query("Salary == Salary.max()")[["Name", "Salary"]]

      Name  Salary
0  DANIYAL  100000

## Filtering Rows Using Multiple Conditions with query()

- and is used for logical AND
- Variables can be referenced using the @ symbol

In [14]:
sal = 50000

filtered = df.query("Salary > @sal and Age > 25")

filtered

      Name  Age  Salary  Performance Score
4  HASNAIN   34   90000                 88
7     PREM   28   78000                 89

## Filtering Rows Using OR with query()

- or is used for logical OR
- Backticks are required for column names containing spaces

In [15]:
filtered2 = df.query("Age > 25 or `Performance Score` > 90")

filtered2

      Name  Age  Salary  Performance Score
3   RAHEEM   56   44000                 92
4  HASNAIN   34   90000                 88
5   QAYOOM   46   34000                 95
6   NABEEL   39   45000                 80
7     PREM   28   78000                 89

## Aggregation Functions

- Aggregation functions summarize data
- They are commonly used for analysis and reporting

## Finding the Maximum Salary

- max() returns the largest value in a column

In [16]:
df["Salary"].max()

100000

## Finding the Minimum Salary

- min() returns the smallest value in a column

In [17]:
df["Salary"].min()

34000

## Calculating the Average Salary

- mean() returns the arithmetic average of values

In [18]:
df["Salary"].mean()

np.float64(64500.0)

## Calculating the Total Salary

- sum() returns the total of all values in a column

In [19]:
df["Salary"].sum()

np.int64(516000)

In [20]:
df

      Name  Age  Salary  Performance Score
0  DANIYAL   20  100000                 85
1     UMAR   24   40000                 90
2    UMAIR   16   85000                 78
3   RAHEEM   56   44000                 92
4  HASNAIN   34   90000                 88
5   QAYOOM   46   34000                 95
6   NABEEL   39   45000                 80
7     PREM   28   78000                 89

## Generating Descriptive Statistics

- describe() generates summary statistics for numerical columns
- It displays count, mean, standard deviation, minimum, maximum, and quartiles

In [21]:
df.describe()

             Age         Salary  Performance Score
count   8.000000       8.000000           8.000000
mean   32.875000   64500.000000          87.125000
std    13.621805   26305.892876           5.817154
min    16.000000   34000.000000          78.000000
25%    23.000000   43000.000000          83.750000
50%    31.000000   61500.000000          88.500000
75%    40.750000   86250.000000          90.500000
max    56.000000  100000.000000          95.000000

## Displaying the Shape of a DataFrame

- shape returns the number of rows and columns
- The result is returned as a tuple
- The first value represents rows
- The second value represents columns

In [22]:
df.shape

(8, 4)

## Extracting the Number of Rows and Columns

- The shape tuple can be unpacked into separate variables
- This provides individual access to rows and columns

In [23]:
rows, columns = df.shape

rows, columns

(8, 4)

## Displaying Column Names

- columns returns all column names in the DataFrame
- It helps inspect the structure of the dataset

In [24]:
df.columns

Index(['Name', 'Age', 'Salary', 'Performance Score'], dtype='object')