# Working with Indexes in Pandas

## Learning Objectives

- Understand what indexes are
- View DataFrame indexes
- Set a custom index
- Reset indexes to default values

In [1]:
import pandas as pd

In [2]:
weather_data = {
    "day": ["1/1/2026", "1/2/2026", "1/3/2026", "1/4/2026", "1/5/2026", "1/6/2026"],
    "temperature": [32, 35, 28, 24, 32, 31],
    "windspeed": [6, 7, 2, 7, 4, 2],
    "event": ["Rain", "Sunny", "Snow", "Snow", "Rain", "Sunny"]
}

df = pd.DataFrame(weather_data)

df

        day  temperature  windspeed  event
0  1/1/2026           32          6   Rain
1  1/2/2026           35          7  Sunny
2  1/3/2026           28          2   Snow
3  1/4/2026           24          7   Snow
4  1/5/2026           32          4   Rain
5  1/6/2026           31          2  Sunny

## Displaying the Index Range

- Every DataFrame has an index
- By default, Pandas assigns integer indexes starting from 0
- The index attribute displays the complete index range

In [3]:
df.index

RangeIndex(start=0, stop=6, step=1)

## Setting a Custom Index

- Any column can be used as an index
- set_index() replaces the default index with values from the specified column
- inplace=True modifies the original DataFrame directly

In [4]:
df.set_index("day", inplace=True)

df

          temperature  windspeed  event
day
1/1/2026           32          6   Rain
1/2/2026           35          7  Sunny
1/3/2026           28          2   Snow
1/4/2026           24          7   Snow
1/5/2026           32          4   Rain
1/6/2026           31          2  Sunny

## Resetting the Index

- reset_index() restores the default integer index

In [5]:
df.reset_index(inplace=True)

df

        day  temperature  windspeed  event
0  1/1/2026           32          6   Rain
1  1/2/2026           35          7  Sunny
2  1/3/2026           28          2   Snow
3  1/4/2026           24          7   Snow
4  1/5/2026           32          4   Rain
5  1/6/2026           31          2  Sunny