# Data Selection with loc, iloc, at, and iat

## Learning Objectives

- Access rows using labels
- Access rows using positions
- Access individual cells
- Slice rows using labels and positions
- Select specific rows and columns
- Understand the difference between loc and iloc
- Understand the difference between at and iat

## Label-Based vs Position-Based Selection

- loc uses row and column labels
- iloc uses row and column positions
- at is a faster version of loc for accessing a single value
- iat is a faster version of iloc for accessing a single value

In [1]:
import pandas as pd

In [2]:
weather_data = {
    "day": ["1/1/2026", "1/2/2026", "1/3/2026", "1/4/2026", "1/5/2026", "1/6/2026"],
    "temperature": [32, 35, 28, 24, 32, 31],
    "windspeed": [6, 7, 2, 7, 4, 2],
    "event": ["Rain", "Sunny", "Snow", "Snow", "Rain", "Sunny"]
}

df = pd.DataFrame(weather_data)

df

        day  temperature  windspeed  event
0  1/1/2026           32          6   Rain
1  1/2/2026           35          7  Sunny
2  1/3/2026           28          2   Snow
3  1/4/2026           24          7   Snow
4  1/5/2026           32          4   Rain
5  1/6/2026           31          2  Sunny

## Setting a Custom Index

- The day column is used as the DataFrame index
- Label-based selection becomes easier with a meaningful index

In [3]:
df.set_index("day", inplace=True)

df

          temperature  windspeed  event
day
1/1/2026           32          6   Rain
1/2/2026           35          7  Sunny
1/3/2026           28          2   Snow
1/4/2026           24          7   Snow
1/5/2026           32          4   Rain
1/6/2026           31          2  Sunny

## Accessing a Single Row Using loc

- loc is used for label-based selection
- Row labels are used instead of numeric positions

In [4]:
df.loc["1/1/2026"]

temperature      32
windspeed         6
event          Rain
Name: 1/1/2026, dtype: object

## Accessing a Single Row Using iloc

- iloc is used for position-based selection
- Numeric indexes are used instead of labels

In [5]:
df.iloc[0]

temperature      32
windspeed         6
event          Rain
Name: 1/1/2026, dtype: object

## Accessing a Single Cell Using loc

- Both row and column labels are specified
- loc returns the value stored at the specified location

In [6]:
df.loc["1/1/2026", "event"]

'Rain'

## Accessing a Single Cell Using iloc

- Both row and column positions are specified
- iloc returns the value stored at the specified position

In [7]:
df.iloc[0, 2]

'Rain'

## Slicing Rows Using loc

- loc performs label-based slicing
- The ending label is included in the result

In [8]:
df.loc["1/1/2026":"1/4/2026"]

          temperature  windspeed  event
day
1/1/2026           32          6   Rain
1/2/2026           35          7  Sunny
1/3/2026           28          2   Snow
1/4/2026           24          7   Snow

## Slicing Rows Using iloc

- iloc performs position-based slicing
- The ending position is excluded from the result

In [9]:
df.iloc[0:4]

          temperature  windspeed  event
day
1/1/2026           32          6   Rain
1/2/2026           35          7  Sunny
1/3/2026           28          2   Snow
1/4/2026           24          7   Snow

## Selecting Specific Rows and Columns Using loc

- Row labels and column names are used together
- Multiple columns can be selected by passing a list

In [10]:
print(df.loc["1/1/2026":"1/4/2026",["temperature","windspeed"]])

          temperature  windspeed
day
1/1/2026           32          6
1/2/2026           35          7
1/3/2026           28          2
1/4/2026           24          7

## Selecting Specific Rows and Columns Using iloc

- Row and column positions are used together
- Position-based indexing is useful when labels are unknown

In [11]:
df.iloc[0:4, 0:2]

          temperature  windspeed
day
1/1/2026           32          6
1/2/2026           35          7
1/3/2026           28          2
1/4/2026           24          7

## Fast Access to a Single Value Using at

- at is optimized for accessing a single value
- It uses row and column labels
- It is faster than loc when retrieving a single cell

In [12]:
df.at["1/1/2026", "temperature"]

np.int64(32)

## Fast Access to a Single Value Using iat

- iat is optimized for accessing a single value
- It uses row and column positions
- It is faster than iloc when retrieving a single cell

In [13]:
df.iat[0, 0]

np.int64(32)