# Adding, Modifying, and Deleting Columns in Pandas

## Learning Objectives

- Add new columns to a DataFrame
- Insert columns at specific positions
- Modify individual cell values
- Update an entire column
- Delete single and multiple columns

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Name": ["DANIYAL", "UMAR", "UMAIR", "RAHEEM", "HASNAIN", "QAYOOM", "NABEEL", "PREM"],
    "Age": [20, 24, 16, 56, 34, 46, 39, 28],
    "Salary": [100000, 40000, 85000, 44000, 90000, 34000, 45000, 78000],
    "Performance Score": [85, 90, 78, 92, 88, 95, 80, 89]
})

df

      Name  Age  Salary  Performance Score
0  DANIYAL   20  100000                 85
1     UMAR   24   40000                 90
2    UMAIR   16   85000                 78
3   RAHEEM   56   44000                 92
4  HASNAIN   34   90000                 88
5   QAYOOM   46   34000                 95
6   NABEEL   39   45000                 80
7     PREM   28   78000                 89

## Adding a New Column at the End

- A new column can be added by assigning values to a new column name
- The column is automatically added at the end of the DataFrame
- Here, Bonus is calculated as 10% of Salary

In [3]:
df["Bonus"] = df["Salary"] * 0.1

df

      Name  Age  Salary  Performance Score    Bonus
0  DANIYAL   20  100000                 85  10000.0
1     UMAR   24   40000                 90   4000.0
2    UMAIR   16   85000                 78   8500.0
3   RAHEEM   56   44000                 92   4400.0
4  HASNAIN   34   90000                 88   9000.0
5   QAYOOM   46   34000                 95   3400.0
6   NABEEL   39   45000                 80   4500.0
7     PREM   28   78000                 89   7800.0

## Inserting a New Column at a Specific Position

- insert() is used to place a column at a specific index
- The first argument specifies the position
- Existing columns shift to the right

In [4]:
df.insert(0,"Employee Id",[10,20,30,40,50,60,70,80])

df

   Employee Id     Name  Age  Salary  Performance Score    Bonus
0           10  DANIYAL   20  100000                 85  10000.0
1           20     UMAR   24   40000                 90   4000.0
2           30    UMAIR   16   85000                 78   8500.0
3           40   RAHEEM   56   44000                 92   4400.0
4           50  HASNAIN   34   90000                 88   9000.0
5           60   QAYOOM   46   34000                 95   3400.0
6           70   NABEEL   39   45000                 80   4500.0
7           80     PREM   28   78000                 89   7800.0

## Modifying a Single Cell Value

- loc is used to access a specific cell
- The value can be updated by assigning a new value

In [5]:
df.loc[1, "Salary"] = 80000

df

   Employee Id     Name  Age  Salary  Performance Score    Bonus
0           10  DANIYAL   20  100000                 85  10000.0
1           20     UMAR   24   80000                 90   4000.0
2           30    UMAIR   16   85000                 78   8500.0
3           40   RAHEEM   56   44000                 92   4400.0
4           50  HASNAIN   34   90000                 88   9000.0
5           60   QAYOOM   46   34000                 95   3400.0
6           70   NABEEL   39   45000                 80   4500.0
7           80     PREM   28   78000                 89   7800.0

## Updating an Entire Column

- A complete column can be updated using vectorized operations
- The operation is applied to all rows in the column
- Here, Salary is increased by 5%

In [6]:
df["Salary"] = df["Salary"] * 1.05

df

   Employee Id     Name  Age    Salary  Performance Score    Bonus
0           10  DANIYAL   20  105000.0                 85  10000.0
1           20     UMAR   24   84000.0                 90   4000.0
2           30    UMAIR   16   89250.0                 78   8500.0
3           40   RAHEEM   56   46200.0                 92   4400.0
4           50  HASNAIN   34   94500.0                 88   9000.0
5           60   QAYOOM   46   35700.0                 95   3400.0
6           70   NABEEL   39   47250.0                 80   4500.0
7           80     PREM   28   81900.0                 89   7800.0

## Deleting a Single Column

- drop() is used to remove columns from a DataFrame
- columns specifies which column should be deleted
- inplace=True updates the original DataFrame

In [7]:
df.drop(columns="Performance Score",inplace=True)

df

   Employee Id     Name  Age    Salary    Bonus
0           10  DANIYAL   20  105000.0  10000.0
1           20     UMAR   24   84000.0   4000.0
2           30    UMAIR   16   89250.0   8500.0
3           40   RAHEEM   56   46200.0   4400.0
4           50  HASNAIN   34   94500.0   9000.0
5           60   QAYOOM   46   35700.0   3400.0
6           70   NABEEL   39   47250.0   4500.0
7           80     PREM   28   81900.0   7800.0

## Deleting Multiple Columns

- Multiple columns can be removed by passing a list
- All specified columns are deleted together

In [8]:
df.drop(columns=["Age","Salary"],inplace=True)

df

   Employee Id     Name    Bonus
0           10  DANIYAL  10000.0
1           20     UMAR   4000.0
2           30    UMAIR   8500.0
3           40   RAHEEM   4400.0
4           50  HASNAIN   9000.0
5           60   QAYOOM   3400.0
6           70   NABEEL   4500.0
7           80     PREM   7800.0