# Renaming, Ranking, and Reordering Data in Pandas

## Learning Objectives

- Rename column names
- Rename row labels
- Assign ranks to data
- Reorder columns
- Change the position of specific columns

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("employee_data.csv", encoding="latin-1")

df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

## Renaming All Column Names

- The columns attribute can be used to replace all column names at once
- The number of new column names must match the number of existing columns

In [3]:
df.columns = ["ID", "NAME", "AGE", "DEPARTMENT", "SALARY"]

df

   ID     NAME  AGE DEPARTMENT  SALARY
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

## Renaming a Specific Column

- rename() is used to change selected column names
- Only the specified columns are renamed

In [4]:
df.rename(columns={
    "SALARY" : "Income"
},inplace=True)

df

   ID     NAME  AGE DEPARTMENT  Income
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

## Renaming a Specific Row Label

- Row labels can also be renamed
- rename() accepts a dictionary of old and new index labels

In [5]:
df.rename(index={
    1 : "FIRST"
},inplace=True)

df

       ID     NAME  AGE DEPARTMENT  Income
0       1    Alice   25         HR   55000
FIRST   2      Bob   32         IT   72000
2       3  Charlie   28    Finance   48000
3       4    David   45  Marketing   91000
4       5      Eva   38         IT   65000
5       6    Frank   29    Finance   50000
6       7    Grace   41         HR   82000
7       8   Hannah   26  Marketing   47000
8       9      Ian   35         IT   75000
9      10    Julia   30    Finance   60000

## Understanding rank()

- rank() assigns a position to each value within a column
- Ranking starts from 1
- Equal values receive the same rank
- It is commonly used in reporting and analytics

## Assigning Ranks in Ascending Order

- rank() assigns rankings based on column values
- Smaller values receive lower ranks
- By default, ranking is performed in ascending order

In [6]:
df["Ranking"] = df["Income"].rank()

df

       ID     NAME  AGE DEPARTMENT  Income  Ranking
0       1    Alice   25         HR   55000      4.0
FIRST   2      Bob   32         IT   72000      7.0
2       3  Charlie   28    Finance   48000      2.0
3       4    David   45  Marketing   91000     10.0
4       5      Eva   38         IT   65000      6.0
5       6    Frank   29    Finance   50000      3.0
6       7    Grace   41         HR   82000      9.0
7       8   Hannah   26  Marketing   47000      1.0
8       9      Ian   35         IT   75000      8.0
9      10    Julia   30    Finance   60000      5.0

## Assigning Ranks in Descending Order

- ascending=False assigns the highest rank to the largest value
- Useful when ranking performance, salary, or scores

In [7]:
df["Ranking"] = df["Income"].rank(ascending=False)

df

       ID     NAME  AGE DEPARTMENT  Income  Ranking
0       1    Alice   25         HR   55000      7.0
FIRST   2      Bob   32         IT   72000      4.0
2       3  Charlie   28    Finance   48000      9.0
3       4    David   45  Marketing   91000      1.0
4       5      Eva   38         IT   65000      5.0
5       6    Frank   29    Finance   50000      8.0
6       7    Grace   41         HR   82000      2.0
7       8   Hannah   26  Marketing   47000     10.0
8       9      Ian   35         IT   75000      3.0
9      10    Julia   30    Finance   60000      6.0

## Reordering Columns

- Columns can be rearranged by providing a new column order
- The DataFrame returns columns in the specified sequence

In [8]:
df = df[["NAME","ID","AGE","DEPARTMENT","Income","Ranking"]]

df

          NAME  ID  AGE DEPARTMENT  Income  Ranking
0        Alice   1   25         HR   55000      7.0
FIRST      Bob   2   32         IT   72000      4.0
2      Charlie   3   28    Finance   48000      9.0
3        David   4   45  Marketing   91000      1.0
4          Eva   5   38         IT   65000      5.0
5        Frank   6   29    Finance   50000      8.0
6        Grace   7   41         HR   82000      2.0
7       Hannah   8   26  Marketing   47000     10.0
8          Ian   9   35         IT   75000      3.0
9        Julia  10   30    Finance   60000      6.0

## Moving a Column to the End

- A custom column order can be created dynamically
- List comprehension is used to exclude the target column
- The target column is then added at the end

In [9]:
new_col_order = [col for col in df.columns if (col != "ID")] + ["ID"]
df = df[new_col_order]

df

          NAME  AGE DEPARTMENT  Income  Ranking  ID
0        Alice   25         HR   55000      7.0   1
FIRST      Bob   32         IT   72000      4.0   2
2      Charlie   28    Finance   48000      9.0   3
3        David   45  Marketing   91000      1.0   4
4          Eva   38         IT   65000      5.0   5
5        Frank   29    Finance   50000      8.0   6
6        Grace   41         HR   82000      2.0   7
7       Hannah   26  Marketing   47000     10.0   8
8          Ian   35         IT   75000      3.0   9
9        Julia   30    Finance   60000      6.0  10