# Handling Missing Values, Interpolation, and Data Cleaning in Pandas

## Learning Objectives

- Detect missing values using isnull()
- Count missing values per column
- Remove missing data using dropna()
- Fill missing values using fillna()
- Apply forward fill and backward fill
- Use interpolation methods for numerical data
- Handle time-based interpolation
- Remove rows based on conditions (how, thresh)
- Reindex DataFrames with date ranges
- Detect and remove duplicate rows

In [1]:
import pandas as pd

## Creating a Sample DataFrame with Missing Values

- This dataset contains NaN and None values
- It is used to demonstrate missing data handling techniques

In [2]:
df = pd.DataFrame({
    "Name" : ["DANIYAL","UMAR","UMAIR","RAHEEM","HASNAIN","QAYOOM","NABEEL","PREM"],
    "Age" : [20,None,16,56,34,46,39,28],
    "Salary": [100000,40000,85000,44000,90000,34000,45000,78000],
    "Performance Score" : [85,None,78,92,88,95,80,89]
})

df

      Name   Age  Salary  Performance Score
0  DANIYAL  20.0  100000               85.0
1     UMAR   NaN   40000                NaN
2    UMAIR  16.0   85000               78.0
3   RAHEEM  56.0   44000               92.0
4  HASNAIN  34.0   90000               88.0
5   QAYOOM  46.0   34000               95.0
6   NABEEL  39.0   45000               80.0
7     PREM  28.0   78000               89.0

## Detecting Missing Values

- isnull() returns True where values are missing
- sum() counts missing values per column

In [3]:
df.isnull()

    Name    Age  Salary  Performance Score
0  False  False   False              False
1  False   True   False               True
2  False  False   False              False
3  False  False   False              False
4  False  False   False              False
5  False  False   False              False
6  False  False   False              False
7  False  False   False              False

In [4]:
df.isnull().sum()

Name                 0
Age                  1
Salary               0
Performance Score    1
dtype: int64

## Removing Missing Values Using dropna()

- dropna() removes rows or columns containing missing values
- axis=0 removes rows
- axis=1 removes columns
- inplace=True modifies the original DataFrame

In [5]:
new_df = df.copy()

new_df.dropna(inplace=True)

new_df

      Name   Age  Salary  Performance Score
0  DANIYAL  20.0  100000               85.0
2    UMAIR  16.0   85000               78.0
3   RAHEEM  56.0   44000               92.0
4  HASNAIN  34.0   90000               88.0
5   QAYOOM  46.0   34000               95.0
6   NABEEL  39.0   45000               80.0
7     PREM  28.0   78000               89.0

## Removing Columns with Missing Values

- axis=1 removes columns containing NaN values

In [6]:
new_df = df.copy()

new_df.dropna(axis=1,inplace=True)

new_df

      Name  Salary
0  DANIYAL  100000
1     UMAR   40000
2    UMAIR   85000
3   RAHEEM   44000
4  HASNAIN   90000
5   QAYOOM   34000
6   NABEEL   45000
7     PREM   78000

## Filling Missing Values Using fillna()

- fillna() replaces missing values with a given value
- Can be used with constants or computed values

In [7]:
new_df = df.copy()

new_df.fillna(0, inplace=True)

new_df

      Name   Age  Salary  Performance Score
0  DANIYAL  20.0  100000               85.0
1     UMAR   0.0   40000                0.0
2    UMAIR  16.0   85000               78.0
3   RAHEEM  56.0   44000               92.0
4  HASNAIN  34.0   90000               88.0
5   QAYOOM  46.0   34000               95.0
6   NABEEL  39.0   45000               80.0
7     PREM  28.0   78000               89.0

## Filling Missing Values with Mean

- Missing values can be replaced with statistical measures
- Mean is commonly used for numerical data

In [8]:
new_df = df.copy()

new_df["Age"].fillna(new_df["Age"].mean(),inplace=True)
new_df["Performance Score"].fillna(new_df["Performance Score"].mean(),inplace=True)

new_df

C:\Users\User\AppData\Local\Temp\ipykernel_8596\3412179120.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_df["Age"].fillna(new_df["Age"].mean(),inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_8596\3412179120.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_df["Performance Score"].fillna(new_df["Performance Score"].mean(),inplace=True)

      Name        Age  Salary  Performance Score
0  DANIYAL  20.000000  100000          85.000000
1     UMAR  34.142857   40000          86.714286
2    UMAIR  16.000000   85000          78.000000
3   RAHEEM  56.000000   44000          92.000000
4  HASNAIN  34.000000   90000          88.000000
5   QAYOOM  46.000000   34000          95.000000
6   NABEEL  39.000000   45000          80.000000
7     PREM  28.000000   78000          89.000000

## Loading Time Series Data

- parse_dates converts string dates into datetime format
- Useful for time-based analysis

In [9]:
df = pd.read_csv("weather_data.csv", parse_dates=["day"], encoding="latin-1")

df.set_index("day", inplace=True)

df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

## Filling Missing Values with Dictionary

- Different columns can have different fill values
- fillna() supports dictionary-based replacement

In [10]:
new_df = df.copy()

new_df.fillna({
    "temperature": 0,
    "windspeed": 0,
    "event": "No event"
}, inplace=True)

new_df

            temperature  windspeed     event
day
2017-01-01         32.0        6.0      Rain
2017-01-04          0.0        9.0     Sunny
2017-01-05         28.0        0.0      Snow
2017-01-06          0.0        7.0  No event
2017-01-07         32.0        0.0      Rain
2017-01-08          0.0        0.0     Sunny
2017-01-09          0.0        0.0  No event
2017-01-10         34.0        8.0    Cloudy
2017-01-11         40.0       12.0     Sunny

## Forward Fill (ffill)

- ffill propagates previous valid value forward
- Useful for time series continuity

In [11]:
new_df = df.copy()

new_df.ffill(inplace=True)

new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        7.0   Sunny
2017-01-09         32.0        7.0   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

## Forward Fill (ffill) with Limit

- ffill fills missing values using the previous valid value
- It moves top to bottom in the column
- limit parameter controls how many NaN values are filled consecutively
- If limit=1, only one missing value in a row will be filled

In [12]:
new_df = df.copy()

new_df.ffill(limit=1, inplace=True)

new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        NaN   Sunny
2017-01-09          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

## Backward Fill (bfill)

- bfill uses next valid value to fill missing data
- Works in reverse direction of ffill

In [13]:
new_df = df.copy()

new_df.bfill(inplace=True)

new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         28.0        9.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         32.0        7.0    Rain
2017-01-07         32.0        8.0    Rain
2017-01-08         34.0        8.0   Sunny
2017-01-09         34.0        8.0  Cloudy
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

## Backward Fill (bfill) with Limit

- bfill fills missing values using the next valid value
- It moves bottom to top in the column
- limit parameter controls how many consecutive NaN values are filled
- If limit=1, only one missing value in a sequence is filled

In [14]:
new_df = df.copy()

new_df.bfill(limit=1, inplace=True)

new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         28.0        9.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         32.0        7.0    Rain
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09         34.0        8.0  Cloudy
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

## Interpolation (Linear Method)

- Interpolation estimates missing values mathematically
- Linear interpolation assumes straight-line change between values

In [15]:
df = pd.DataFrame({
    "Time": [1, 2, 3, 4, 5],
    "Value": [10, None, 30, None, 50]
})

df.interpolate(method="linear", inplace=True)

df

   Time  Value
0     1   10.0
1     2   20.0
2     3   30.0
3     4   40.0
4     5   50.0

In [16]:
df = pd.read_csv("weather_data.csv",parse_dates=["day"],encoding="latin-1")

df.set_index("day",inplace=True)

df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

## Interpolation (Default Method - Linear)

- interpolate() fills missing values using mathematical estimation
- Default method is linear interpolation
- It assumes values change in a straight line between points
- Works mainly on numerical data

In [17]:
new_df = df.copy()

new_df.interpolate(inplace=True)

new_df

C:\Users\User\AppData\Local\Temp\ipykernel_8596\279900517.py:3: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df.interpolate(inplace=True)

            temperature  windspeed   event
day
2017-01-01    32.000000       6.00    Rain
2017-01-04    30.000000       9.00   Sunny
2017-01-05    28.000000       8.00    Snow
2017-01-06    30.000000       7.00     NaN
2017-01-07    32.000000       7.25    Rain
2017-01-08    32.666667       7.50   Sunny
2017-01-09    33.333333       7.75     NaN
2017-01-10    34.000000       8.00  Cloudy
2017-01-11    40.000000      12.00   Sunny

## Time-Based Interpolation

- method="time" considers time gaps between values
- Works only with datetime index

In [18]:
new_df = df.copy()

new_df.interpolate(method="time",inplace=True)

new_df

C:\Users\User\AppData\Local\Temp\ipykernel_8596\772024741.py:3: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df.interpolate(method="time",inplace=True)

            temperature  windspeed   event
day
2017-01-01    32.000000       6.00    Rain
2017-01-04    29.000000       9.00   Sunny
2017-01-05    28.000000       8.00    Snow
2017-01-06    30.000000       7.00     NaN
2017-01-07    32.000000       7.25    Rain
2017-01-08    32.666667       7.50   Sunny
2017-01-09    33.333333       7.75     NaN
2017-01-10    34.000000       8.00  Cloudy
2017-01-11    40.000000      12.00   Sunny

## Dropping Rows Based on Conditions

- how="all" removes rows where all values are missing
- thresh keeps rows with minimum number of valid values

In [19]:
new_df = df.copy()

new_df.dropna(how="all", inplace=True)

new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [20]:
new_df = df.copy()

new_df.dropna(thresh=1, inplace=True)

new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [21]:
new_df = df.copy()

new_df.dropna(thresh=2, inplace=True)

new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-07         32.0        NaN    Rain
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

## Reindexing with Date Range

- reindex() aligns DataFrame with new index
- date_range creates continuous date sequence

In [22]:
dt = pd.date_range("01-01-2017", "01-11-2017")
idx = pd.DatetimeIndex(dt)

df = df.reindex(idx)

df

            temperature  windspeed   event
2017-01-01         32.0        6.0    Rain
2017-01-02          NaN        NaN     NaN
2017-01-03          NaN        NaN     NaN
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [23]:
df = pd.DataFrame({
    "day": ["1/1/2026", "1/2/2026", "1/3/2026", "1/4/2026", "1/5/2026", "1/6/2026", "1/1/2026", "1/3/2026", "1/5/2026", "1/6/2026"],
    "temperature": [32, 35, 28, 24, 32, 31, 32, 28, 32, 31],
    "windspeed":   [6, 7, 2, 7, 4, 2, 6, 2, 4, 2],
    "event": ["Rain", "Sunny", "Snow", "Snow", "Rain", "Sunny", "Rain", "Snow", "Rain", "Sunny"]
})

df

        day  temperature  windspeed  event
0  1/1/2026           32          6   Rain
1  1/2/2026           35          7  Sunny
2  1/3/2026           28          2   Snow
3  1/4/2026           24          7   Snow
4  1/5/2026           32          4   Rain
5  1/6/2026           31          2  Sunny
6  1/1/2026           32          6   Rain
7  1/3/2026           28          2   Snow
8  1/5/2026           32          4   Rain
9  1/6/2026           31          2  Sunny

## Detecting Duplicate Rows

- duplicated() returns True for repeated rows
- Useful for data cleaning

In [24]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool

## Removing Duplicate Rows

- drop_duplicates() removes repeated rows
- Keeps first occurrence by default

In [25]:
df.drop_duplicates(inplace=True)

df

        day  temperature  windspeed  event
0  1/1/2026           32          6   Rain
1  1/2/2026           35          7  Sunny
2  1/3/2026           28          2   Snow
3  1/4/2026           24          7   Snow
4  1/5/2026           32          4   Rain
5  1/6/2026           31          2  Sunny