# Data Replacement, Mapping, Apply, and Assign in Pandas

## Learning Objectives

- Replace invalid or impossible values using replace()
- Handle multiple replacement conditions
- Use regex-based replacement
- Convert categorical values into numeric form
- Understand map() for Series transformation
- Use apply() for row/element-wise operations
- Create new columns using apply() and lambda
- Use assign() for functional-style DataFrame updates

In [1]:
import numpy as np
import pandas as pd

## Loading Weather Dataset

- Dataset contains incorrect placeholder values
- Used to demonstrate data cleaning techniques

In [2]:
df1 = pd.read_csv("weatherData.csv", encoding="latin-1")

df1

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -88888   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

## Replacing Single Invalid Values

- replace() is used to convert invalid placeholders into NaN
- -99999 often represents missing or incorrect data

In [3]:
new_df = df1.copy()

new_df.replace(-99999, np.nan, inplace=True)

new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0   -88888.0   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

## Replacing Multiple Invalid Values

- Multiple values can be replaced at once
- Useful for cleaning inconsistent datasets

In [4]:
new_df = df1.copy()

new_df.replace([-99999, -88888], np.nan, inplace=True)

new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

## Column-Specific Replacement Using Dictionary

- Different columns can have different replacement rules
- Helps in structured data cleaning

In [5]:
new_df = df1.copy()

new_df.replace({
    "temperature": -99999,
    "windspeed": [-99999, -88888],
    "event": "0"
}, np.nan, inplace=True)

new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0    NaN

In [6]:
df2 = pd.read_csv("weatherData2.csv", encoding="latin-1")

df2

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  No Event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34          5  No Event

## Mixed Value Replacement

- Can replace both numeric and text values together
- Useful for real-world messy datasets

In [7]:
new_df = df2.copy()

new_df.replace({
    -99999: np.nan,
    "No Event": "Sunny"
}, inplace=True)

new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0  Sunny
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0  Sunny

In [8]:
df3 = pd.read_csv("weatherData3.csv", encoding="latin-1")

df3

        day temperature windspeed     event
0  1/1/2017        32 F     6 mph      Rain
1  1/2/2017      -99999     7 mph     Sunny
2  1/3/2017          28    -99999      Snow
3  1/4/2017      -99999         7  No Event
4  1/5/2017        32 C    -88888      Rain
5  1/6/2017          31         2     Sunny
6  1/6/2017          34         5  No Event

## Regex-Based Replacement

- regex=True allows pattern-based replacement
- Useful for cleaning non-numeric characters from data

In [9]:
new_df = df3.copy()

new_df.replace({
    "temperature": "[A-Za-z]",
    "windspeed": "[A-Za-z]"
}, "", regex=True, inplace=True)

new_df

        day temperature windspeed     event
0  1/1/2017         32         6       Rain
1  1/2/2017      -99999        7      Sunny
2  1/3/2017          28    -99999      Snow
3  1/4/2017      -99999         7  No Event
4  1/5/2017         32     -88888      Rain
5  1/6/2017          31         2     Sunny
6  1/6/2017          34         5  No Event

## Replacing Multiple Categories with Numeric Values

- Converts categorical labels into numeric scores
- Useful for ML preprocessing

In [10]:
df = pd.DataFrame({
    "Score": ["exceptional", "average", "good", "poor", "average", "exceptional"],
    "Student": ["Daniyal", "Umair", "Umar", "Raheem", "Hasnain", "Tariq"]
})

df.replace(
    ["poor", "average", "good", "exceptional"],
    [1, 2, 3, 4],
    inplace=True
)

df

C:\Users\User\AppData\Local\Temp\ipykernel_4464\2337341581.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(

   Score  Student
0      4  Daniyal
1      2    Umair
2      3     Umar
3      1   Raheem
4      2  Hasnain
5      4    Tariq

## Mapping Values Using map()

- map() replaces values using a dictionary
- Works only on Series
- Commonly used for encoding categorical data

In [11]:
df = pd.DataFrame({
    "Score": ["exceptional", "average", "good", "poor", "average", "exceptional"],
    "Student": ["Daniyal", "Umair", "Umar", "Raheem", "Hasnain", "Tariq"]
})

score_map = {"exceptional": 4, "average": 3, "good": 2, "poor": 1}

df["Score"] = df["Score"].map(score_map)

df

   Score  Student
0      4  Daniyal
1      3    Umair
2      2     Umar
3      1   Raheem
4      3  Hasnain
5      4    Tariq

## Using apply() for Conditional Transformation

- apply() applies a function to each element
- Supports lambda functions
- Used for creating new derived columns

In [12]:
df = pd.read_csv("employee_data.csv", encoding="latin-1")

df["Tax"] = df["Salary"].apply(lambda x: "20%" if x > 60000 else "10%")

df

   ID     Name  Age Department  Salary  Tax
0   1    Alice   25         HR   55000  10%
1   2      Bob   32         IT   72000  20%
2   3  Charlie   28    Finance   48000  10%
3   4    David   45  Marketing   91000  20%
4   5      Eva   38         IT   65000  20%
5   6    Frank   29    Finance   50000  10%
6   7    Grace   41         HR   82000  20%
7   8   Hannah   26  Marketing   47000  10%
8   9      Ian   35         IT   75000  20%
9  10    Julia   30    Finance   60000  10%

## Using assign() to Create New Columns

- assign() adds new columns without modifying original DataFrame directly
- Returns a new DataFrame
- Useful for functional-style coding

In [13]:
df = pd.read_csv("employee_data.csv", encoding="latin-1")

df = df.assign(New_Salary=df["Salary"] * 1.1)

df

   ID     Name  Age Department  Salary  New_Salary
0   1    Alice   25         HR   55000     60500.0
1   2      Bob   32         IT   72000     79200.0
2   3  Charlie   28    Finance   48000     52800.0
3   4    David   45  Marketing   91000    100100.0
4   5      Eva   38         IT   65000     71500.0
5   6    Frank   29    Finance   50000     55000.0
6   7    Grace   41         HR   82000     90200.0
7   8   Hannah   26  Marketing   47000     51700.0
8   9      Ian   35         IT   75000     82500.0
9  10    Julia   30    Finance   60000     66000.0