# Sorting Data in Pandas

## Learning Objectives

- Sort data using a single column
- Sort data in ascending order
- Sort data in descending order
- Sort data using multiple columns
- Understand the ascending parameter

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Name": ["DANIYAL", "UMAIR", "TARIQ"],
    "Age": [20, 22, 19],
    "Salary": [20000, 10000, 30000]
})

df

      Name  Age  Salary
0  DANIYAL   20   20000
1    UMAIR   22   10000
2    TARIQ   19   30000

## Sorting Data Based on a Single Column

- sort_values() is used to sort data in a DataFrame
- A specific column is provided as the sorting key
- ascending=True sorts data in ascending order
- inplace=True updates the original DataFrame

In [3]:
df.sort_values("Age", ascending=True, inplace=True)

df

      Name  Age  Salary
2    TARIQ   19   30000
0  DANIYAL   20   20000
1    UMAIR   22   10000

## Sorting Data in Descending Order

- ascending=False sorts values from largest to smallest
- The sorting is performed on the specified column

In [4]:
df.sort_values("Age", ascending=False, inplace=True)

df

      Name  Age  Salary
1    UMAIR   22   10000
0  DANIYAL   20   20000
2    TARIQ   19   30000

## Creating a DataFrame for Multi-Column Sorting

- Multiple columns can be used as sorting keys
- If values in the first column are the same, Pandas uses the next column for sorting

In [5]:
df2 = pd.DataFrame({
    "Name": ["DANIYAL", "UMAIR", "TARIQ"],
    "Age": [20, 20, 20],
    "Salary": [20000, 10000, 30000]
})

df2

      Name  Age  Salary
0  DANIYAL   20   20000
1    UMAIR   20   10000
2    TARIQ   20   30000

## Sorting Data Based on Multiple Columns

- Multiple column names are passed as a list
- The ascending parameter can also accept a list
- Each True or False value corresponds to a specific column
- Pandas first sorts by Age and then by Salary

In [6]:
df2.sort_values(
    ["Age", "Salary"],
    ascending=[True, True],
    inplace=True
)

df2

      Name  Age  Salary
1    UMAIR   20   10000
0  DANIYAL   20   20000
2    TARIQ   20   30000