# GroupBy and Aggregation in Pandas

## Learning Objectives

- Group data using single and multiple columns
- Apply aggregation functions like sum, mean, max
- Iterate through grouped data
- Access specific groups
- Use describe() on grouped data
- Apply multiple aggregations using agg()
- Rename aggregated columns

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Name": ["DANIYAL", "UMAIR", "TARIQ", "RAHEEM", "UMAR"],
    "Age": [20, 24, 22, 24, 20],
    "Salary": [50000, 60000, 45000, 52000, 40000]
})

df

      Name  Age  Salary
0  DANIYAL   20   50000
1    UMAIR   24   60000
2    TARIQ   22   45000
3   RAHEEM   24   52000
4     UMAR   20   40000

## Grouping Data by a Single Column

- groupby() is used to split data into groups
- Aggregation function sum() is applied to each group
- Here data is grouped by Age

In [3]:
df.groupby("Age")["Salary"].sum()

Age
20     90000
22     45000
24    112000
Name: Salary, dtype: int64

## Grouping Data by Multiple Columns

- Data can be grouped using more than one column
- Each combination of Age and Name forms a group

In [4]:
df.groupby(["Age", "Name"])["Salary"].sum()

Age  Name
20   DANIYAL    50000
     UMAR       40000
22   TARIQ      45000
24   RAHEEM     52000
     UMAIR      60000
Name: Salary, dtype: int64

In [5]:
df = pd.read_csv("weather_by_cities.csv", encoding="latin-1")

df

         day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

## Finding Maximum Temperature by City

- groupby() splits data by city
- max() returns the highest temperature in each group

In [6]:
df.groupby("city")["temperature"].max()

city
mumbai      92
new york    36
paris       54
Name: temperature, dtype: int64

## Finding Average Wind Speed by City

- mean() calculates the average wind speed for each city

In [7]:
df.groupby("city")["windspeed"].mean()

city
mumbai       9.25
new york     8.00
paris       12.75
Name: windspeed, dtype: float64

## Iterating Through Groups

- groupby() creates grouped objects
- Each group can be iterated using a loop
- Each iteration returns a city name and its corresponding DataFrame

In [8]:
g = df.groupby("city")

for city, city_df in g:
    print(city)
    print(city_df)

mumbai
        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
new york
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
paris
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy

## Accessing a Specific Group

- get_group() retrieves data for a specific group
- Useful when working with large grouped datasets

In [9]:
g.get_group("mumbai")

        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

## Descriptive Statistics for Each Group

- describe() provides summary statistics for each group
- Includes count, mean, min, max, and quartiles

In [10]:
g.describe()

         temperature                                                   \
               count   mean       std   min    25%   50%    75%   max
city
mumbai           4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0

         windspeed
             count   mean       std  min   25%   50%    75%   max
city
mumbai         4.0   9.25  5.057997  5.0  5.00   8.5  12.75  15.0
new york       4.0   8.00  2.708013  6.0  6.75   7.0   8.25  12.0
paris          4.0  12.75  5.251984  8.0  9.50  11.5  14.75  20.0

## Applying Multiple Aggregations on One Column

- agg() allows multiple aggregation functions
- Useful for detailed analysis of a single column

In [11]:
df.groupby("city")["temperature"].agg(["mean", "max", "min"])

           mean  max  min
city
mumbai    88.50   92   85
new york  32.25   36   28
paris     47.75   54   42

## Applying Multiple Aggregations with Custom Column Names

- Column names can be renamed during aggregation
- Makes output more readable and meaningful

In [12]:
df.groupby("city")["temperature"].agg(avg_temperature="mean",max_temperature="max",min_temperature="min")

          avg_temperature  max_temperature  min_temperature
city
mumbai              88.50               92               85
new york            32.25               36               28
paris               47.75               54               42

## Aggregation on Multiple Columns

- Different aggregation functions can be applied to different columns
- Each column can have its own function

In [13]:
df.groupby("city").agg({
    "temperature": "mean",
    "windspeed": "max"
})

          temperature  windspeed
city
mumbai          88.50         15
new york        32.25         12
paris           47.75         20

## Aggregation with Multiple Columns and Custom Names

- Output columns can be renamed while aggregating
- Tuple format is used: (column, function)

In [14]:
df.groupby("city").agg(
    avg_temperature=("temperature", "mean"),
    max_windspeed=("windspeed", "max")
)

          avg_temperature  max_windspeed
city
mumbai              88.50             15
new york            32.25             12
paris               47.75             20