# Merging DataFrames in Pandas

## Learning Objectives

- Combine multiple DataFrames
- Understand different types of joins
- Perform Inner, Outer, Left, Right, and Cross Joins
- Identify the source of merged data
- Handle common column names using suffixes

In [1]:
import pandas as pd

## Creating Customer and Order DataFrames

- Two DataFrames are created for demonstrating merge operations
- Both DataFrames contain a common column named Customer Id

In [2]:
df1 = pd.DataFrame({
    "Customer Id": [1, 2, 4],
    "Name": ["DANIYAL", "UMAIR", "TARIQ"]
})

df2 = pd.DataFrame({
    "Customer Id": [1, 2, 3],
    "Order Amount": [250, 450, 350]
})

df1

   Customer Id     Name
0            1  DANIYAL
1            2    UMAIR
2            4    TARIQ

In [3]:
df2

   Customer Id  Order Amount
0            1           250
1            2           450
2            3           350

## Inner Join

- Returns only matching records from both DataFrames
- Rows without matching values are excluded
- inner is the most commonly used join type

In [4]:
merged = pd.merge(df1,df2,on="Customer Id",how="inner")

merged

   Customer Id     Name  Order Amount
0            1  DANIYAL           250
1            2    UMAIR           450

## Outer Join

- Returns all rows from both DataFrames
- Non-matching values are filled with NaN
- Combines matching and non-matching records

In [5]:
merged = pd.merge(df1,df2,on="Customer Id",how="outer")

merged

   Customer Id     Name  Order Amount
0            1  DANIYAL         250.0
1            2    UMAIR         450.0
2            3      NaN         350.0
3            4    TARIQ           NaN

## Using Indicator with Outer Join

- indicator=True adds a column named _merge
- It identifies the source of each row
- left_only means the row exists only in the left DataFrame
- right_only means the row exists only in the right DataFrame
- both means the row exists in both DataFrames

In [6]:
merged = pd.merge(df1,df2,on="Customer Id",how="outer",indicator=True)

merged

   Customer Id     Name  Order Amount      _merge
0            1  DANIYAL         250.0        both
1            2    UMAIR         450.0        both
2            3      NaN         350.0  right_only
3            4    TARIQ           NaN   left_only

## Left Join

- Returns all rows from the left DataFrame
- Matching rows are taken from the right DataFrame
- Non-matching values are filled with NaN

In [7]:
merged = pd.merge(df1,df2,on="Customer Id",how="left")

merged

   Customer Id     Name  Order Amount
0            1  DANIYAL         250.0
1            2    UMAIR         450.0
2            4    TARIQ           NaN

## Right Join

- Returns all rows from the right DataFrame
- Matching rows are taken from the left DataFrame
- Non-matching values are filled with NaN

In [8]:
merged = pd.merge(df1,df2,on="Customer Id",how="right")

merged

   Customer Id     Name  Order Amount
0            1  DANIYAL           250
1            2    UMAIR           450
2            3      NaN           350

## Cross Join

- Creates all possible combinations of rows
- Every row from the first DataFrame is matched with every row from the second DataFrame
- Also known as the Cartesian Product

In [9]:
merged = pd.merge(df1,df2,how="cross")

merged

   Customer Id_x     Name  Customer Id_y  Order Amount
0              1  DANIYAL              1           250
1              1  DANIYAL              2           450
2              1  DANIYAL              3           350
3              2    UMAIR              1           250
4              2    UMAIR              2           450
5              2    UMAIR              3           350
6              4    TARIQ              1           250
7              4    TARIQ              2           450
8              4    TARIQ              3           350

## Merging DataFrames with Common Columns

- Both DataFrames contain columns with the same names
- The city column is used as the merge key
- Inner Join is the default merge type

In [10]:
df1 = pd.DataFrame({
    "city": ["Karachi", "Hyderabad", "Islamabad", "Quetta"],
    "temperature": [30, 37, 25, 15],
    "humidity": [65, 68, 71, 75]
})

df2 = pd.DataFrame({
    "city": ["Hyderabad", "Karachi", "Peshawar"],
    "temperature": [30, 37, 25],
    "humidity": [65, 68, 71]
})

df1

        city  temperature  humidity
0    Karachi           30        65
1  Hyderabad           37        68
2  Islamabad           25        71
3     Quetta           15        75

In [11]:
df2

        city  temperature  humidity
0  Hyderabad           30        65
1    Karachi           37        68
2   Peshawar           25        71

## Merging on a Common Column

- Pandas automatically performs an Inner Join when how is not specified
- Only matching city values are included

In [12]:
merged = pd.merge(df1,df2,on="city")

merged

        city  temperature_x  humidity_x  temperature_y  humidity_y
0    Karachi             30          65             37          68
1  Hyderabad             37          68             30          65

## Handling Duplicate Column Names Using Suffixes

- Both DataFrames contain temperature and humidity columns
- suffixes are added to distinguish columns with identical names
- This prevents column name conflicts after merging

In [13]:
merged = pd.merge(df1,df2,on="city",suffixes=["_left","_right"])

merged

,city,temperature_left,humidity_left,temperature_right,humidity_right
0,Karachi,30,65,37,68
1,Hyderabad,37,68,30,65