# Concatenation in Pandas

## Learning Objectives

- Combine multiple DataFrames using concat()
- Understand vertical (row-wise) concatenation
- Understand horizontal (column-wise) concatenation
- Use keys for hierarchical indexing
- Access individual concatenated sections
- Concatenate DataFrame with Series
- Understand index alignment in concatenation

In [1]:
import pandas as pd

## Creating Sample DataFrames (Region-wise Data)

- Two separate DataFrames represent different regions
- Each contains customer information

In [2]:
df1 = pd.DataFrame({
    "Customer Id": [1, 2],
    "Name": ["DANIYAL", "UMAIR"]
})

df2 = pd.DataFrame({
    "Customer Id": [3, 4],
    "Name": ["RAHEEM", "UMAR"]
})

df1

   Customer Id     Name
0            1  DANIYAL
1            2    UMAIR

In [3]:
df2

   Customer Id    Name
0            3  RAHEEM
1            4    UMAR

## Vertical Concatenation (Row-wise)

- axis=0 stacks DataFrames vertically
- This is the default behavior of concat()
- ignore_index=True resets index after merging

In [4]:
df_concat = pd.concat([df1, df2], ignore_index=True)

df_concat

   Customer Id     Name
0            1  DANIYAL
1            2    UMAIR
2            3   RAHEEM
3            4     UMAR

## Concatenation with Keys (Hierarchical Indexing)

- keys create a multi-level index
- Each DataFrame gets a label (region1, region2)
- Useful for identifying data sources after merging

In [5]:
df_concat = pd.concat([df1, df2], keys=["region1", "region2"])

df_concat

           Customer Id     Name
region1 0            1  DANIYAL
        1            2    UMAIR
region2 0            3   RAHEEM
        1            4     UMAR

## Accessing a Specific Region After Concatenation

- loc[] is used to access a specific key group
- Works only when keys are used

In [6]:
df_concat.loc["region1"]

   Customer Id     Name
0            1  DANIYAL
1            2    UMAIR

## Horizontal Concatenation (Column-wise)

- axis=1 combines DataFrames side by side
- Index alignment is important for correct merging

In [7]:
temperature_df = pd.DataFrame({
    "city": ["Hyderabad", "Islamabad", "Karachi"],
    "temperature": [35, 25, 30]
}, index=[0, 1, 2])

windspeed_df = pd.DataFrame({
    "city": ["Islamabad", "Karachi", "Hyderabad"],
    "windspeed": [7, 12, 9]
}, index=[1, 2, 0])

temperature_df

        city  temperature
0  Hyderabad           35
1  Islamabad           25
2    Karachi           30

In [8]:
windspeed_df

        city  windspeed
1  Islamabad          7
2    Karachi         12
0  Hyderabad          9

## Concatenating DataFrames Horizontally

- axis=1 aligns data based on index values
- Columns are combined side by side

In [9]:
df_concat = pd.concat([temperature_df, windspeed_df], axis=1)

df_concat

        city  temperature       city  windspeed
0  Hyderabad           35  Hyderabad          9
1  Islamabad           25  Islamabad          7
2    Karachi           30    Karachi         12

## Concatenating a Series with a DataFrame

- Series can also be combined with DataFrames
- It is treated as a new column
- Index alignment is applied automatically

In [10]:
df = pd.DataFrame({
    "city": ["Islamabad", "Karachi", "Hyderabad"],
    "windspeed": [7, 12, 9]
})

s = pd.Series(["Rain", "Dry", "Humid"], name="Event")

df_concat = pd.concat([df, s], axis=1)

df_concat

        city  windspeed  Event
0  Islamabad          7   Rain
1    Karachi         12    Dry
2  Hyderabad          9  Humid