# Pivot, Pivot Table, and Melt in Pandas

## Learning Objectives

- Transform data using pivot (long → wide format)
- Use pivot_table for aggregation and summarization
- Apply grouping with pivot_table
- Use Grouper for time-based aggregation
- Reshape data using melt (wide → long format)
- Customize melted column names
- Understand structured data reshaping techniques

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("weather.csv")

df

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/2/2017  new york           66        58
2  5/3/2017  new york           68        60
3  5/1/2017    mumbai           75        80
4  5/2/2017    mumbai           78        83
5  5/3/2017    mumbai           82        85
6  5/1/2017   beijing           80        26
7  5/2/2017   beijing           77        30
8  5/3/2017   beijing           79        35

## Pivot: Reshaping Data (Long → Wide Format)

- pivot() transforms long-form data into wide format
- index becomes rows
- columns become column headers
- values fill the table

In [3]:
df.pivot(index="date", columns="city")

         temperature                 humidity
city         beijing mumbai new york  beijing mumbai new york
date
5/1/2017          80     75       65       26     80       56
5/2/2017          77     78       66       30     83       58
5/3/2017          79     82       68       35     85       60

## Pivot with Specific Values

- values parameter selects which column to display
- Only selected metric is shown in pivot table

In [4]:
df.pivot(index="date", columns="city", values="humidity")

city      beijing  mumbai  new york
date
5/1/2017       26      80        56
5/2/2017       30      83        58
5/3/2017       35      85        60

## Pivot Table for Aggregation

- pivot_table() is used for summarization
- It automatically handles duplicate values using aggregation
- Default aggregation function is mean

In [5]:
df.pivot_table(index="city", columns="date", aggfunc="max")

         humidity                   temperature
date     5/1/2017 5/2/2017 5/3/2017    5/1/2017 5/2/2017 5/3/2017
city
beijing        26       30       35          80       77       79
mumbai         80       83       85          75       78       82
new york       56       58       60          65       66       68

## Pivot Table with Margins

- margins=True adds row and column totals
- Provides overall aggregated values

In [6]:
df.pivot_table(index="city", columns="date", margins=True)

         humidity                              temperature             \
date     5/1/2017 5/2/2017 5/3/2017        All    5/1/2017   5/2/2017
city
beijing      26.0     30.0     35.0  30.333333   80.000000  77.000000
mumbai       80.0     83.0     85.0  82.666667   75.000000  78.000000
new york     56.0     58.0     60.0  58.000000   65.000000  66.000000
All          54.0     57.0     60.0  57.000000   73.333333  73.666667


date       5/3/2017        All
city
beijing   79.000000  78.666667
mumbai    82.000000  78.333333
new york  68.000000  66.333333
All       76.333333  74.444444

## Time-Based Grouping Using Grouper

- Grouper is used for time-based aggregation
- freq="M" groups data by month
- Requires datetime format for proper grouping

In [7]:
df = pd.read_csv("weather3.csv", parse_dates=["date"])

df

        date      city  temperature  humidity
0 2017-05-01  new york           65        56
1 2017-05-02  new york           61        54
2 2017-05-03  new york           70        60
3 2017-12-01  new york           30        50
4 2017-12-02  new york           28        52
5 2017-12-03  new york           25        51

In [8]:
df.pivot_table(index=pd.Grouper(freq="M",key="date"),columns="city")

C:\Users\User\AppData\Local\Temp\ipykernel_4664\281373624.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.pivot_table(index=pd.Grouper(freq="M",key="date"),columns="city")

             humidity temperature
city         new york    new york
date
2017-05-31  56.666667   65.333333
2017-12-31  51.000000   27.666667

## Reshaping Data Using Melt (Wide → Long Format)

- melt() converts wide data into long format
- Useful for normalization and analysis

In [9]:
df = pd.read_csv("days_weather.csv")

df

         day  chicago  chennai  berlin
0     Monday       32       75      41
1    Tuesday       30       77      43
2  Wednesday       28       75      45
3   Thursday       22       82      38
4     Friday       30       83      30
5   Saturday       20       81      45
6     Sunday       25       77      47

## Basic Melt Operation

- id_vars keeps identifier columns fixed
- Other columns are unpivoted into rows

In [10]:
df1 = pd.melt(df, id_vars="day")

df1

          day variable  value
0      Monday  chicago     32
1     Tuesday  chicago     30
2   Wednesday  chicago     28
3    Thursday  chicago     22
4      Friday  chicago     30
5    Saturday  chicago     20
6      Sunday  chicago     25
7      Monday  chennai     75
8     Tuesday  chennai     77
9   Wednesday  chennai     75
10   Thursday  chennai     82
11     Friday  chennai     83
12   Saturday  chennai     81
13     Sunday  chennai     77
14     Monday   berlin     41
15    Tuesday   berlin     43
16  Wednesday   berlin     45
17   Thursday   berlin     38
18     Friday   berlin     30
19   Saturday   berlin     45
20     Sunday   berlin     47

## Filtering Melted Data

- Melted data can be filtered like a normal DataFrame
- Useful for extracting specific city data

In [11]:
df1[df1["variable"] == "chicago"]

         day variable  value
0     Monday  chicago     32
1    Tuesday  chicago     30
2  Wednesday  chicago     28
3   Thursday  chicago     22
4     Friday  chicago     30
5   Saturday  chicago     20
6     Sunday  chicago     25

## Melt with Custom Column Names

- var_name renames variable column
- value_name renames value column
- Improves readability

In [12]:
df2 = pd.melt(df,id_vars="day",var_name="city",value_name="temperature")

df2

          day     city  temperature
0      Monday  chicago           32
1     Tuesday  chicago           30
2   Wednesday  chicago           28
3    Thursday  chicago           22
4      Friday  chicago           30
5    Saturday  chicago           20
6      Sunday  chicago           25
7      Monday  chennai           75
8     Tuesday  chennai           77
9   Wednesday  chennai           75
10   Thursday  chennai           82
11     Friday  chennai           83
12   Saturday  chennai           81
13     Sunday  chennai           77
14     Monday   berlin           41
15    Tuesday   berlin           43
16  Wednesday   berlin           45
17   Thursday   berlin           38
18     Friday   berlin           30
19   Saturday   berlin           45
20     Sunday   berlin           47

## Advanced Melt Example with Multiple ID Variables

- Multiple columns can be preserved using id_vars list
- Specific columns can be melted using value_vars

In [13]:
df = pd.DataFrame({
    "country": ["USA", "USA", "India", "India"],
    "year": [2020, 2021, 2020, 2021],
    "sales": [100, 120, 90, 110],
    "profit": [20, 25, 18, 22],
    "tax": [2, 4, 1, 3]
})

df

  country  year  sales  profit  tax
0     USA  2020    100      20    2
1     USA  2021    120      25    4
2   India  2020     90      18    1
3   India  2021    110      22    3

## Melt with Multiple Value Variables

- Multiple metrics can be melted at once
- var_name stores metric names
- value_name stores actual values

In [14]:
pd.melt(
    df,
    id_vars=["country", "year"],
    value_vars=["sales", "profit"],
    var_name="metrics",
    value_name="value"
)

  country  year metrics  value
0     USA  2020   sales    100
1     USA  2021   sales    120
2   India  2020   sales     90
3   India  2021   sales    110
4     USA  2020  profit     20
5     USA  2021  profit     25
6   India  2020  profit     18
7   India  2021  profit     22