# Time Series Analysis in Pandas

## Learning Objectives

- Understand time series data structure
- Work with datetime index
- Slice data using date ranges
- Perform resampling (monthly, yearly, etc.)
- Generate custom date ranges
- Use business day frequency
- Apply forward filling for missing dates
- Shift and lag time series data
- Calculate returns and changes in stock prices

In [1]:
import pandas as pd

## Loading Time Series Data (Apple Stock)

- Date column is converted into datetime format
- Date is set as index for time-based operations

In [2]:
df = pd.read_csv("Apple.csv", parse_dates=["Date"], index_col="Date")

df.head()

C:\Users\User\AppData\Local\Temp\ipykernel_5732\2889294345.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv("Apple.csv", parse_dates=["Date"], index_col="Date")

              Open    High     Low   Close    Volume
Date
2017-07-07  142.90  144.75  142.90  144.18  19201712
2017-07-06  143.02  143.50  142.41  142.73  24128782
2017-07-05  143.69  144.79  142.72  144.09  21569557
2017-07-03  144.88  145.30  143.10  143.50  14277848
2017-06-30  144.45  144.96  143.78  144.02  23024107

## Accessing Data Using Date Index

- Individual date selection is possible using loc[]
- Partial string indexing allows filtering by year/month

In [3]:
df.loc["2017-01-10"]

Open           118.77
High           119.38
Low            118.30
Close          119.11
Volume    24462051.00
Name: 2017-01-10 00:00:00, dtype: float64

In [4]:
df.loc["2017-01"]

              Open    High     Low   Close    Volume
Date
2017-01-31  121.15  121.39  120.62  121.35  49200993
2017-01-30  120.93  121.63  120.66  121.63  30377503
2017-01-27  122.14  122.35  121.60  121.95  20562944
2017-01-26  121.67  122.44  121.60  121.94  26337576
2017-01-25  120.42  122.10  120.28  121.88  32586673
2017-01-24  119.55  120.10  119.50  119.97  23211038
2017-01-23  120.00  120.81  119.77  120.08  22050218
2017-01-20  120.45  120.45  119.73  120.00  32597892
2017-01-19  119.40  120.09  119.37  119.78  25597291
2017-01-18  120.00  120.50  119.71  119.99  23712961
2017-01-17  118.34  120.24  118.22  120.00  34439843
2017-01-13  119.11  119.62  118.81  119.04  26111948
2017-01-12  118.90  119.30  118.21  119.25  27086220
2017-01-11  118.74  119.93  118.60  119.75  27588593
2017-01-10  118.77  119.38  118.30  119.11  24462051
2017-01-09  117.95  119.43  117.94  118.99  33561948
2017-01-06  116.78  118.16  116.47  117.91  31751900
2017-01-05  115.92  116.86  115.81  116.61  22193587
2017-01-04  115.85  116.51  115.75  116.02  21118116
2017-01-03  115.80  116.33  114.76  116.15  28781865

## Monthly Average Closing Price

- Mean closing price is calculated for a specific month
- Useful for trend analysis

In [5]:
df.loc["2017-01", "Close"].mean()

np.float64(119.57000000000001)

## Resampling Time Series Data

- resample() groups data based on time intervals
- "M" represents monthly frequency
- Useful for aggregating time-based data

In [6]:
df["Close"].resample("M").mean()

C:\Users\User\AppData\Local\Temp\ipykernel_5732\167506527.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df["Close"].resample("M").mean()

Date
2016-07-31     99.473333
2016-08-31    107.665217
2016-09-30    110.857143
2016-10-31    115.707143
2016-11-30    110.154286
2016-12-31    114.335714
2017-01-31    119.570000
2017-02-28    133.713684
2017-03-31    140.617826
2017-04-30    142.886842
2017-05-31    152.227727
2017-06-30    147.831364
2017-07-31    143.625000
Freq: ME, Name: Close, dtype: float64

## Generating Custom Date Range

- date_range() creates a sequence of dates
- freq="B" represents business days (Monday–Friday)

In [7]:
df = pd.read_csv("Aapl_no_dates.csv")

df.head()

     Open    High     Low   Close    Volume
0  153.17  153.33  152.22  153.18  16404088
1  153.58  155.45  152.89  155.45  27770715
2  154.34  154.45  153.46  153.93  25331662
3  153.90  155.81  153.78  154.45  26624926
4  155.02  155.98  154.48  155.37  21069647

In [8]:
rng = pd.date_range(start="6/1/2017", end="6/30/2017", freq="B")

df.set_index(rng, inplace=True)

df.head()

              Open    High     Low   Close    Volume
2017-06-01  153.17  153.33  152.22  153.18  16404088
2017-06-02  153.58  155.45  152.89  155.45  27770715
2017-06-05  154.34  154.45  153.46  153.93  25331662
2017-06-06  153.90  155.81  153.78  154.45  26624926
2017-06-07  155.02  155.98  154.48  155.37  21069647

## Slicing Time Series Data

- Date ranges can be used for filtering rows
- Useful for analyzing specific periods

In [9]:
df["2017-06-01":"2017-06-10"]

              Open    High     Low   Close    Volume
2017-06-01  153.17  153.33  152.22  153.18  16404088
2017-06-02  153.58  155.45  152.89  155.45  27770715
2017-06-05  154.34  154.45  153.46  153.93  25331662
2017-06-06  153.90  155.81  153.78  154.45  26624926
2017-06-07  155.02  155.98  154.48  155.37  21069647
2017-06-08  155.25  155.54  154.40  154.99  21250798
2017-06-09  155.19  155.19  146.02  148.98  64882657

## Calculating Mean for a Date Range

- Mean is calculated for selected time window

In [10]:
df["2017-06-01":"2017-06-10"].Close.mean()

np.float64(153.7642857142857)

## Handling Missing Dates with asfreq()

- asfreq() ensures continuous date frequency
- Missing dates can be filled using forward fill (pad)

In [11]:
df.asfreq("D", method="pad")

              Open    High     Low   Close    Volume
2017-06-01  153.17  153.33  152.22  153.18  16404088
2017-06-02  153.58  155.45  152.89  155.45  27770715
2017-06-03  153.58  155.45  152.89  155.45  27770715
2017-06-04  153.58  155.45  152.89  155.45  27770715
2017-06-05  154.34  154.45  153.46  153.93  25331662
2017-06-06  153.90  155.81  153.78  154.45  26624926
2017-06-07  155.02  155.98  154.48  155.37  21069647
2017-06-08  155.25  155.54  154.40  154.99  21250798
2017-06-09  155.19  155.19  146.02  148.98  64882657
2017-06-10  155.19  155.19  146.02  148.98  64882657
2017-06-11  155.19  155.19  146.02  148.98  64882657
2017-06-12  145.74  146.09  142.51  145.42  72307330
2017-06-13  147.16  147.45  145.15  146.59  34165445
2017-06-14  147.50  147.50  143.84  145.16  31531232
2017-06-15  143.32  144.48  142.21  144.29  32165373
2017-06-16  143.78  144.50  142.20  142.27  50361093
2017-06-17  143.78  144.50  142.20  142.27  50361093
2017-06-18  143.78  144.50  142.20  142.27  50361093
2017-06-19  143.66  146.74  143.66  146.34  32541404
2017-06-20  146.87  146.87  144.94  145.01  24900073
2017-06-21  145.52  146.07  144.61  145.87  21265751
2017-06-22  145.77  146.70  145.12  145.63  19106294
2017-06-23  145.13  147.16  145.11  146.28  35439389
2017-06-24  145.13  147.16  145.11  146.28  35439389
2017-06-25  145.13  147.16  145.11  146.28  35439389
2017-06-26  147.17  148.28  145.38  145.82  25692361
2017-06-27  145.01  146.16  143.62  143.73  24761891
2017-06-28  144.49  146.11  143.16  145.83  22082432
2017-06-29  144.71  145.13  142.28  143.68  31499368
2017-06-30  144.45  144.96  143.78  144.02  23024107

## Generating Business Day Ranges

- freq="B" generates business days only
- Useful for financial datasets

In [12]:
rng = pd.date_range(start="1/1/2026", periods=30, freq="B")

rng

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-05', '2026-01-06',
               '2026-01-07', '2026-01-08', '2026-01-09', '2026-01-12',
               '2026-01-13', '2026-01-14', '2026-01-15', '2026-01-16',
               '2026-01-19', '2026-01-20', '2026-01-21', '2026-01-22',
               '2026-01-23', '2026-01-26', '2026-01-27', '2026-01-28',
               '2026-01-29', '2026-01-30', '2026-02-02', '2026-02-03',
               '2026-02-04', '2026-02-05', '2026-02-06', '2026-02-09',
               '2026-02-10', '2026-02-11'],
              dtype='datetime64[ns]', freq='B')

## Custom Business Calendar (US Holidays Example)

- CustomBusinessDay excludes holidays
- Useful for real-world financial modeling

In [13]:
from pandas.tseries.holiday import USFederalHolidayCalendar
from pandas.tseries.offsets import CustomBusinessDay

usb = CustomBusinessDay(calendar=USFederalHolidayCalendar())

In [14]:
df = pd.read_csv("Aapl_no_date.csv")

rng = pd.date_range(start="7/1/2017", end="7/21/2017", freq=usb)

df.set_index(rng, inplace=True)

df.head()

              Open    High     Low   Close    Volume
2017-07-03  144.88  145.30  143.10  143.50  14277848
2017-07-05  143.69  144.79  142.72  144.09  21569557
2017-07-06  143.02  143.50  142.41  142.73  24128782
2017-07-07  142.90  144.75  142.90  144.18  19201712
2017-07-10  144.11  145.95  143.37  145.06  21090636

## Shifting and Lagging Data

- shift() moves data forward or backward in time
- Used for comparison between time periods

In [15]:
df = pd.read_csv("Fb.csv", parse_dates=["Date"], index_col="Date")

df

C:\Users\User\AppData\Local\Temp\ipykernel_5732\1078551045.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv("Fb.csv", parse_dates=["Date"], index_col="Date")

             Price
Date
2017-08-15  171.00
2017-08-16  170.00
2017-08-17  166.91
2017-08-18  167.41
2017-08-21  167.78
2017-08-22  169.64
2017-08-23  168.71
2017-08-24  167.74
2017-08-25  166.32
2017-08-28  167.24

## Applying Shift Function

- shift(1) moves data forward
- shift(-1) moves data backward

In [16]:
df.shift(1)

             Price
Date
2017-08-15     NaN
2017-08-16  171.00
2017-08-17  170.00
2017-08-18  166.91
2017-08-21  167.41
2017-08-22  167.78
2017-08-23  169.64
2017-08-24  168.71
2017-08-25  167.74
2017-08-28  166.32

In [17]:
df.shift(-1)

             Price
Date
2017-08-15  170.00
2017-08-16  166.91
2017-08-17  167.41
2017-08-18  167.78
2017-08-21  169.64
2017-08-22  168.71
2017-08-23  167.74
2017-08-24  166.32
2017-08-25  167.24
2017-08-28     NaN

## Calculating Price Changes

- Previous day price is created using shift()
- Difference shows daily change in stock price

In [18]:
df["Previous Day Price"] = df["Price"].shift(1)

df["1 day change"] = df["Price"] - df["Previous Day Price"]

df

             Price  Previous Day Price  1 day change
Date
2017-08-15  171.00                 NaN           NaN
2017-08-16  170.00              171.00         -1.00
2017-08-17  166.91              170.00         -3.09
2017-08-18  167.41              166.91          0.50
2017-08-21  167.78              167.41          0.37
2017-08-22  169.64              167.78          1.86
2017-08-23  168.71              169.64         -0.93
2017-08-24  167.74              168.71         -0.97
2017-08-25  166.32              167.74         -1.42
2017-08-28  167.24              166.32          0.92

## Calculating Percentage Returns

- Shows percentage change over 5 days
- Useful for financial analysis

In [19]:
df["5 day return %"] = (df["Price"] - df["Price"].shift(5)) * 100 / df["Price"].shift(5)

df

             Price  Previous Day Price  1 day change  5 day return %
Date
2017-08-15  171.00                 NaN           NaN             NaN
2017-08-16  170.00              171.00         -1.00             NaN
2017-08-17  166.91              170.00         -3.09             NaN
2017-08-18  167.41              166.91          0.50             NaN
2017-08-21  167.78              167.41          0.37             NaN
2017-08-22  169.64              167.78          1.86       -0.795322
2017-08-23  168.71              169.64         -0.93       -0.758824
2017-08-24  167.74              168.71         -0.97        0.497274
2017-08-25  166.32              167.74         -1.42       -0.651096
2017-08-28  167.24              166.32          0.92       -0.321850